### ISSUE TITLE
Documentation gets lost under large examples

### ISSUE THREAD

**Issue by hackartisan** [danieltbrennan/puam-api-docs#1]
Hi! Our team (DRDS) over in https://github.com/pulibrary recently used your API as part of a technical interview and first of all thank you for this documentation! It would have been impossible to use the API without it.

The side effect is that we basically user-tested this repository on a bunch of people, including ourselves! We found that we and our candidates often got lost in the long examples and frequently didn't realize that there was more API documentation below. In the case of the objects endpoint, for example, this meant that people often didn't see the "get multiple objects" documentation.

I wonder if mitigating this could be as simple as adding a table of contents to the top, or briefly summarizing each endpoint / parameter first and then going into more detail in sections for, e.g. "examples" and "data schemas".

**Comment by danieltbrennan** [comment]
This is a great issue and I agree the documentation is long overdue for some improved formatting/cleanup. Assigning this to myself so that we can put it into one of our upcoming sprints and get it addressed. Will update once there's something to look at so we can get your feedback before merge.
